import os
import json
import subprocess


def get_git_diff():
    try:
        with open("temp_diff.txt", "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        print(f"Error reading diff file: {e}")
        return ""


def load_json_file(file_path):
    if not os.path.exists(file_path):
        return {}
    with open(file_path, "r") as f:
        return json.load(f)


import google.generativeai as genai

genai.configure(api_key=os.environ.get("GEMINI_API_KEY", ""))

def actual_ai_analysis(diff):
    
    if not os.environ.get("GEMINI_API_KEY"):
        print("Warning: GEMINI_API_KEY not set. Falling back to mock analysis to prevent crash.")
        return {"vulnerabilities": []}

    prompt = f"""
    You are an expert Application Security Engineer.
    Analyze the following code diff. Detect any security vulnerabilities such as hardcoded credentials, command injection, XSS, etc.
    Return ONLY valid JSON in this exact format, with no markdown formatting or extra text:

    {{
      "vulnerabilities": [
        {{
          "type": "Vulnerability Name",
          "cwe": "CWE-XXX",
          "severity": "High/Critical/Medium/Low",
          "confidence": 0.95,
          "explanation": "Explanation of the issue found in the diff.",
          "secure_fix": "Suggested secure code fix."
        }}
      ]
    }}
    
    If no vulnerabilities are found, return: {{"vulnerabilities": []}}

    Code Diff:
    {diff}
    """
    
    try:
        model = genai.GenerativeModel("gemini-1.5-pro")
        response = model.generate_content(prompt)
        content = response.text.strip()
        
        # Clean up in case the LLM returned markdown blocks
        if content.startswith("```json"):
            content = content[7:]
        if content.endswith("```"):
            content = content[:-3]
            
        return json.loads(content.strip())
    except Exception as e:
        print(f"Error calling Gemini API: {e}")
        return {"vulnerabilities": []}


def calculate_risk(severity, confidence):

    weights = {
        "Low": 1,
        "Medium": 2,
        "High": 3,
        "Critical": 4
    }

    return weights.get(severity, 1) * confidence


def generate_markdown_summary(result):
    
    total_vulns = len(result["vulnerabilities"])
    
    md = f"## 🛡️ AI Security Analysis Report\n\n"
    
    if total_vulns == 0:
        md += "✅ **No high-risk vulnerabilities detected by AI.**\n\n"
        md += "> The Gemini AI analyzer reviewed the latest changes and found no issues.\n"
        return md
        
    md += f"⚠️ **Found {total_vulns} potential security issue(s)**\n\n"
    
    md += "| Type | Severity | CWE | Explanation | Fix |\n"
    md += "|---|---|---|---|---|\n"
    
    for v in result["vulnerabilities"]:
        md += f"| **{v['type']}** | {v['severity']} | {v['cwe']} | {v['explanation']} | `{v['secure_fix']}` |\n"
        
    md += "\n> Note: This report was generated by Gemini AI Security Analyzer.\n"
    return md


def generate_pr_comment(result):
    total_vulns = len(result["vulnerabilities"])
    if total_vulns == 0:
        return ""
        
    md = f"## 🤖 AI Auto-Remediation Suggestions\n\n"
    md += f"I have analyzed your pull request and found **{total_vulns}** potential security issue(s). Here are the suggested fixes:\n\n"
    
    for i, v in enumerate(result["vulnerabilities"], 1):
        md += f"### {i}. **{v['type']}** ({v['severity']} Severity)\n"
        md += f"- **Explanation**: {v['explanation']}\n"
        md += f"- **CWE**: {v['cwe']}\n"
        md += f"- **Suggested Fix**:\n"
        md += f"  > `{v['secure_fix']}`\n\n"
        
    return md


if __name__ == "__main__":

    diff = get_git_diff()

    if not diff.strip():
        print("No changes detected.")
        exit(0)

    result = actual_ai_analysis(diff)

    print(json.dumps(result, indent=2))
    
    # Save for dashboard artifact
    with open("ai-report.json", "w") as f:
        json.dump(result, f, indent=2)

    # Write to GitHub Step Summary
    summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_file:
        with open(summary_file, "a") as f:
            f.write(generate_markdown_summary(result))

    # Generate PR Comment File
    pr_comment_content = generate_pr_comment(result)
    if pr_comment_content:
        with open("pr_comment.md", "w") as f:
            f.write(pr_comment_content)

    # Adaptive enforcement gate
    blocked = False
    for v in result["vulnerabilities"]:
        risk = calculate_risk(v["severity"], v["confidence"])
        print(f"Risk Score: {risk}")

        if risk >= 3:
            blocked = True
            
    if blocked:
        print("🚨 AI Security Gate BLOCKED deployment")
        exit(1)
